### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by NelleV** [computorg/published-202301-chagneux-macrolitter#3]
## Phase 1: acceptance

When the Associate Editor (AE) is satisfied with the author's answers to the reviewers comments, he/she exchanges with authors  that (via the discussion tool on Scholastica)

- [x] authors are informed of the final acceptance 
- [x] affiliation, author-url, affiliation-url and other metadata are correctly filled in on the author git repository
- [x] **Optional! - at the authors' discretion -** the manuscript is formatted using the latest Computo extension
- [x] CI/github-action validates the reproducibility of the manuscript

The authors inform the AE upon completion of the tasks required on their side.
 
## Phase 2: production start-up

- [x] the AE creates a **private** repository in computorg's group named `published-yearmonth-first_author_last_named_manuscript_key`, with CC-by 4 licence
- [x] the AE asks the editor a DOI for this publication
- [x] the Editor add an entry to the `in_production.bib` so that the manuscript appears "in the pipeline" here https://computo.sfds.asso.fr/publications/
- [x] the AE makes a copy of the authors' repository (without the history: `clone --depth 1`) into the above repository
- [x] the AE, assisted by the technical team, ensure that CI works
- [x] the AE, assisted by the technical team, ensures that the last version of [quarto template](https://github.com/computorg/computo-quarto-extension) is used, seeting metadata appropriately (draft: false, repos, doi, etc.)
- [x] the AE formats the exchanges between authors and reviewers as an Issue in the repository, [following this model](https://github.com/computorg/published-paper-tsne/issues/4)
- [x] the AE requests validation from the reviewers for the publication of the reports and  asks if reviewers want to remain anonymous or not
- [x] the AE completes the README.md according to [this template](https://github.com/computorg/published-paper-tsne/blob/main/README.md), with the appropriate badges

## Phase 3: final publication

Once the above tasks are completed, then do

- [x] the AE turns the private repository into a public repository (could be done as soon as a DOI is available)
- [x] the AE makes an Issue asking for final proofreading by the authors (possibly with some minor additional questions), made as a pull-request on Computorg's repository

Once the manuscript is proofreaded (Issue closed)

- [x] the AE informs the Editor who tags the firstly published version
- [x] the Editor moves the BibTeX entry from file "in production" to "published" son Computo website, by completing if needed
- [x] the Editor makes the usual communication of the new publication
